
$LIB_VERSION = 'nvtt-2.1.1+wildfiregames.4'

# Path to the build-artifacts generated by vcpkg
$VcpkgOutLocation = Resolve-Path ".\vcpkg\vc\$VCPKG_TRIPLET"

Write-Output ""
Write-Output "Building nvtt ($LIB_VERSION)"
Write-Output "======================================="
Push-Location $PSScriptRoot

if (!(Test-NeedsBuilding -LibVersion $LIB_VERSION)) {
  Pop-Location
  return
} else {
  Remove-Item -Path .\bin     -Recurse -ErrorAction SilentlyContinue
  Remove-Item -Path .\build   -Recurse -ErrorAction SilentlyContinue
  Remove-Item -Path .\include -Recurse -ErrorAction SilentlyContinue
  Remove-Item -Path .\lib     -Recurse -ErrorAction SilentlyContinue
}

# Code is pre-patched, so we don't need to apply any patches

Write-Output ""
Write-Output "Configuring Build"
Write-Output "---------------------------------------"
New-Item -Path . -Name 'build' -ItemType Directory | Out-Null
Push-Location '.\build'
cmake ..\src `
  -A $env:MSVCPlatform `
  -DCMAKE_INSTALL_PREFIX="$PSScriptRoot" `
  -DPNG_PNG_INCLUDE_DIR="$VcpkgOutLocation\include" `
  -DPNG_LIBRARY="$VcpkgOutLocation\lib\libpng16.lib" `
  -DNVTT_SHARED="1" `
  -DZLIB_INCLUDE_DIR="$VcpkgOutLocation\include" `
  -DZLIB_LIBRARY="$VcpkgOutLocation\lib\zlib.lib" `
  -T "v141_xp"
Pop-Location


Write-Output ""
Write-Output "Build (Release)"
Write-Output "---------------------------------------"
New-Item -Path . -Name 'install' -ItemType Directory | Out-Null
& $env:msbuild '.\build\INSTALL.vcxproj' /v:q /p:PlatformToolset=v141_xp /p:Configuration=RelWithDebInfo


Write-Output ""
Write-Output "Export build artifacts"
Write-Output "---------------------------------------"
Merge-ChildItems -Path .\bin -Destination $env:BIN_DIR_RELEASE
Merge-ChildItems -Path .\bin -Destination $env:BIN_DIR_DEBUG
Write-Output "Done."


Write-BuiltFile -LibVersion $LIB_VERSION
Pop-Location
