name: Win32 Full Build
on:
  workflow_dispatch:
  push:
    branches:
    - build-win32-pyro

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        #- windows-2019
        - windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    # Remove items not needed for building to clear space on the VM
    # (The VM has a 14 GB disc, 0AD checkout consumes ~9.8 GB, the below clears ~9.4 GB)
    - name: Remove unnecessary items
      run: |
        Remove-Item -Path ${{ github.workspace }}\.git -Recurse -Force
        Remove-Item -Path ${{ github.workspace }}\binaries\data\mods\public -Recurse

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Run script file
      run: |
        cd ${{ github.workspace }}\libraries\win32
        .\build-win32-libs.ps1

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    # Clear space on the VM in preparation for the pyrogenesis build
    # (Currently clears ~2.49 GB)
    - name: Delete SpiderMonkey build tree
      run: |
        Remove-Item -Path ${{ github.workspace }}\libraries\source\spidermonkey\mozjs-78.6.0 -Recurse

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Find msbuild
      id: msbuild
      run: |
        $msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "::set-output name=msbuild::$msbuild"

    - name: Update workspaces
      run: |
        chdir build\workspaces
        & .\update-workspaces.bat --atlas --build-shared-glooxwrapper

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Build pyrogenesis (Debug)
      run: |
        $msbuild = "${{ steps.msbuild.outputs.msbuild }}"
        chdir build\workspaces\vs2017
        & $msbuild pyrogenesis.sln /v:q /p:XPDeprecationWarning=false /p:PlatformToolset=v141_xp /t:pyrogenesis /t:AtlasUI /t:test /p:Configuration=Debug

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Build pyrogenesis (Release)
      run: |
        $msbuild = "${{ steps.msbuild.outputs.msbuild }}"
        chdir build\workspaces\vs2017
        & $msbuild pyrogenesis.sln /v:q /p:XPDeprecationWarning=false /p:PlatformToolset=v141_xp /t:pyrogenesis /t:AtlasUI /t:test /p:Configuration=Release

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Print folder contents
      if: ${{ always() }}
      run: |
        (Get-ChildItem -Path "${{ github.workspace }}\binaries\system" -Recurse).FullName

    - name: Run test (Debug)
      run: |
        chdir binaries\system\debug
        Start-Process -FilePath .\test_dbg.exe -Wait -NoNewWindow

    - name: Run test (Release)
      if: ${{ always() }}
      run: |
        chdir binaries\system\release
        Start-Process -FilePath .\test.exe -Wait -NoNewWindow

    - name: Package
      uses: actions/upload-artifact@v2
      with:
        name: pyrogenesis_debug
        path: |
          binaries\system\debug\*.exe
          binaries\system\debug\*.dll
          binaries\system\debug\*.pdb

    - name: Package
      uses: actions/upload-artifact@v2
      with:
        name: pyrogenesis_release
        path: |
          binaries\system\release\*.exe
          binaries\system\release\*.dll
          binaries\system\release\*.pdb
