name: Win32 Full Build
on:
  workflow_dispatch:
  push:
    branches:
    - build-win32-pyro

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        #- windows-2019
        - windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    # Remove items not needed for building to clear space on the VM
    # (The VM has 14 GB drives, 0AD consumes ~9.8 GB, the below clears ~9.4 GB)
    - name: Remove unnecessary items
      run: |
        Remove-Item -Path ${{ github.workspace }}\.git -Recurse -Force
        Remove-Item -Path ${{ github.workspace }}\binaries\data\mods\public -Recurse

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Run script file
      run: |
        cd ${{ github.workspace }}\libraries\win32
        .\build-win32-libs.ps1

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    # Clear space on the VM in preparation for the pyrogenesis build
    # (Currently clears ~2.49 GB)
    - name: Delete SpiderMonkey build tree
      run: |
        Remove-Item -Path ${{ github.workspace }}\libraries\source\spidermonkey\mozjs-78.6.0 -Recurse

    - name: Print locations
      if: ${{ always() }}
      run: |
        (Get-ChildItem -Path "${{ github.workspace }}\libraries\win32\vcpkg\vc\x86-windows\include").FullName
        echo "----"
        (Get-ChildItem -Path "${{ github.workspace }}\libraries\win32\vcpkg\vc\x86-windows\lib").FullName
        echo "----"
        (Get-ChildItem -Path "${{ github.workspace }}\libraries\win32\vcpkg\vc\x86-windows\debug\lib").FullName

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Find msbuild
      id: msbuild
      run: |
        $msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "::set-output name=msbuild::$msbuild"

    - name: Update workspaces
      run: |
        chdir build\workspaces
        & .\update-workspaces.bat --atlas --build-shared-glooxwrapper

    - name: Print vcxproj contents
      run: |
        Get-Content "build\workspaces\vs2017\AtlasUI.vcxproj"

    - name: Print pkgconf output
      if: ${{ always() }}
      run: |
        $env:PKG_CONFIG_PATH = "${{ github.workspace }}\libraries\source\pkgconfig\debug"
        & "$env:PKG_CONFIG_PATH\..\pkgconf.exe" --cflags "libcurl"
        & "$env:PKG_CONFIG_PATH\..\pkgconf.exe" --libs "libcurl"

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Build pyrogenesis (Debug)
      run: |
        $msbuild = "${{ steps.msbuild.outputs.msbuild }}"
        chdir build\workspaces\vs2017
        & $msbuild pyrogenesis.sln /p:XPDeprecationWarning=false /p:PlatformToolset=v141_xp /t:pyrogenesis /t:AtlasUI /t:test /p:Configuration=Debug

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Build pyrogenesis (Release)
      run: |
        $msbuild = "${{ steps.msbuild.outputs.msbuild }}"
        chdir build\workspaces\vs2017
        & $msbuild pyrogenesis.sln /p:XPDeprecationWarning=false /p:PlatformToolset=v141_xp /t:pyrogenesis /t:AtlasUI /t:test /p:Configuration=Release

    - name: Check disk space
      run: |
        (Get-Item $PSScriptRoot).PSDrive

    - name: Print folder contents
      if: ${{ always() }}
      run: |
        (Get-ChildItem -Path "${{ github.workspace }}\binaries\system" -Recurse).FullName
