name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install and Build vcpkg locally
      run: |
        md $env:VCPKG_ROOT
        cd $env:VCPKG_ROOT
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git --branch=2021.05.12 .
        .\bootstrap-vcpkg.bat -disableMetrics

    - name: Sanity check
      shell: bash
      run: |
        echo $VCPKG_ROOT
        ls $VCPKG_ROOT

    - name: Help
      run: |
        $env:VCPKG_ROOT\vcpkg help

    - name: Help install
      run: |
        $env:VCPKG_ROOT\vcpkg help install

    - name: Help integrate
      run: |
        $env:VCPKG_ROOT\vcpkg help integrate

    - name: Help export
      run: |
        $env:VCPKG_ROOT\\cpkg help export

    # Not available from vcpkg: FCollada, Gloox, SpiderMonkey
    - name: Install some packages
      run: >
        $VCPKG_ROOT\vcpkg install
        libvorbis
        pkgconf
        opengl

        #~ boost
        #~ enet
        #~ fmt
        #~ curl
        #~ icu
        #~ libiconv
        #~ libpng
        #~ libsodium
        #~ libvorbis
        #~ libxml2
        #~ minupnpc
        #~ nvtt
        #~ openal-soft
        #~ opengl # or (mesa)
        #~ wxwidgets
        #~ zlib

    - name: Package built stuff
      uses: actions/upload-artifact@v2
      with:
        name: installed
        path: |
          ${{ env.VCPKG_ROOT }}\installed

    - name: Package scripts
      uses: actions/upload-artifact@v2
      with:
        name: scripts
        path: |
          ${{ env.VCPKG_ROOT }}\scripts

    
          #${{ env.VCPKG_ROOT }}
          #!${{ env.VCPKG_ROOT }}\buildtrees
          #!${{ env.VCPKG_ROOT }}\downloads
          #!${{ env.VCPKG_ROOT }}\packages
