name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc'
  INSTALL_DIR: '${{ github.workspace }}\win32'

# Notes for PowerShell novices (like me):
# 
# * To access Environment variables
#   > $env:<NAME>
#   (where <NAME> is the variable name)
#
# * PowerShell doesn't recognise the following as paths:
#   > $env:<PATH>/subpath
#   > $env:<PATH>\subpath
#   Instead, prefix the "call operator", like so:
#   > & $env:<PATH>/subpath
#   > & $env:<PATH>\subpath


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-2019
        - windows-2016

    steps:

    - name: Acquire pyrogenesis.exe
      run: |
        Invoke-WebRequest -Uri 'https://trac.wildfiregames.com/export/25821/ps/trunk/binaries/system/pyrogenesis.exe' -Method Get -OutFile 'pyrogenesis.exe'

    - name: Find dumpbin
      run: |
        $HostArch = 'HostX64'
        $TargetArch = 'x86'
        $dumpbin = @(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\$HostArch\$TargetArch\dumpbin.exe)[-1]
        echo $dumpbin
        echo ""
        & $dumpbin .\pyrogenesis.exe
        echo ""
        & $dumpbin /DEPENDENTS .\pyrogenesis.exe
