name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc'
  INSTALL_DIR: '${{ github.workspace }}\win32'

# Notes for PowerShell novices (like me):
# 
# * To access Environment variables
#   > $env:<NAME>
#   (where <NAME> is the variable name)
#
# * PowerShell doesn't recognise the following as paths:
#   > $env:<PATH>/subpath
#   > $env:<PATH>\subpath
#   Instead, prefix the "call operator", like so:
#   > & $env:<PATH>/subpath
#   > & $env:<PATH>\subpath


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-2019
        - windows-2016

    steps:

    - name: Find dumpbin (**\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\dumpbin.exe)

    - name: Find dumpbin (bin\**\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find bin\**\dumpbin.exe)

    - name: Find dumpbin (HostX64\**\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find HostX64\**\dumpbin.exe)

    - name: Find dumpbin (**\HostX64\**\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\HostX64\**\dumpbin.exe)

    - name: Find dumpbin (HostX64\x86\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find HostX64\x86\dumpbin.exe)

    - name: Find dumpbin (bin\HostX64\x86\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find bin\HostX64\x86\dumpbin.exe)

    - name: Find dumpbin (**\bin\HostX64\x86\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\bin\HostX64\x86\dumpbin.exe)

    - name: Find dumpbin (**\HostX64\x86\)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\HostX64\x86\dumpbin.exe)
