name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc'
  INSTALL_DIR: '${{ github.workspace }}\win32'

# Notes for PowerShell novices (like me):
# 
# * To access Environment variables
#   > $env:<NAME>
#   (where <NAME> is the variable name)
#
# * PowerShell doesn't recognise the following as paths:
#   > $env:<PATH>/subpath
#   > $env:<PATH>\subpath
#   Instead, prefix the "call operator", like so:
#   > & $env:<PATH>/subpath
#   > & $env:<PATH>\subpath


jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install and Build vcpkg locally
      run: |
        md $env:VCPKG_ROOT
        cd $env:VCPKG_ROOT
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git --branch=2021.05.12 .
        .\bootstrap-vcpkg.bat -disableMetrics

    - name: Sanity check
      shell: bash
      run: |
        echo $VCPKG_ROOT
        ls $VCPKG_ROOT

    - name: Sanity check
      run: |
        echo "1> "+$VCPKG_ROOT
        echo "2> "+$env:VCPKG_ROOT

    - name: Help triplet
      run: |
        & $env:VCPKG_ROOT\vcpkg help triplet

    # Not available from vcpkg: FCollada, Gloox, SpiderMonkey
    - name: Install some packages
      run: >
        & $env:VCPKG_ROOT\vcpkg install
        --x-install-root=$env:INSTALL_DIR
        pkgconf
        mesa

        #~ boost
        #~ enet
        #~ fmt
        #~ curl
        #~ icu
        #~ libiconv
        #~ libpng
        #~ libsodium
        #~ libvorbis
        #~ libxml2
        #~ minupnpc
        #~ nvtt
        #~ openal-soft
        #~ opengl # or (mesa)
        #~ wxwidgets
        #~ zlib

    - name: Package built stuff (old)
      uses: actions/upload-artifact@v2
      with:
        name: installed_old
        path: |
          ${{ env.VCPKG_ROOT }}\installed

    - name: Package built stuff (new)
      uses: actions/upload-artifact@v2
      with:
        name: installed_new
        path: |
          ${{ env.INSTALL_DIR }}
