name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

jobs:
  build:
    runs-on: windows-latest

    #env:
      #sourceDir: '${{ github.workspace }}/source/'
      #buildDir: '${{ github.workspace }}/build/'

    steps:
    #- name: Install CMake
    #  uses: lukka/get-cmake@v3.20.1

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v7.3
      with:
        setupOnly: true
        vcpkgDirectory: '${{ github.workspace }}\vcpkg'
        vcpkgGitCommitId: 38d2893b30d4d4b3c09485216ecf4f6e8ef35d88

    - shell: bash
      run: |
        echo $VCPKG_ROOT
        ls $VCPKG_ROOT
        mkdir -p "$VCPKG_ROOT\ports\vorbis"

    - name: Install vorbis
      run: |
        $VCPKG_ROOT/vcpkg install vorbis:x86-windows
      shell: bash

    - name: Package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: vorbis
        path: ${{ env.VCPKG_ROOT }}
