name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc\'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install and Build vcpkg locally
      run: |
        md $env:VCPKG_ROOT
        cd $env:VCPKG_ROOT
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git --branch=2021.05.12 .
        .\bootstrap-vcpkg.bat -disableMetrics

    - name: Sanity check
      shell: bash
      run: |
        echo $VCPKG_ROOT
        ls $VCPKG_ROOT

    # Not available from vcpkg: FCollada, Gloox, SpiderMonkey
    - name: Install some packages
      shell: bash
      run: >
        $VCPKG_ROOT/vcpkg install
        libvorbis
        pkgconf

        #~ boost
        #~ enet
        #~ curl
        #~ icu
        #~ libiconv
        #~ libpng
        #~ libsodium
        #~ libvorbis
        #~ libxml2
        #~ nvtt
        #~ openal-soft
        #~ zlib

    - name: Package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: built_stuff
        path: |
          ${{ env.VCPKG_ROOT }}
          !${{ env.VCPKG_ROOT }}\buildtrees
          !${{ env.VCPKG_ROOT }}\downloads
          !${{ env.VCPKG_ROOT }}\packages
