name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc\'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install and Build vcpkg locally
      run: |
        md $env:VCPKG_ROOT
        cd $env:VCPKG_ROOT
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git --branch=2021.05.12 .
        .\bootstrap-vcpkg.bat -disableMetrics

    - name: Sanity check
      shell: bash
      run: |
        echo $VCPKG_ROOT
        ls $VCPKG_ROOT

    - name: Install some packages
      run: |
        $VCPKG_ROOT/vcpkg install openal-soft
      shell: bash

    - name: Package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: vorbis
        path: ${{ env.VCPKG_ROOT }}
