name: vcpkg tests

on:
  workflow_dispatch:
  push:
    branches:
    - vcpkg

env:
  VCPKG_ROOT: '${{ github.workspace }}\vc'
  INSTALL_DIR: '${{ github.workspace }}\win32'

# Notes for PowerShell novices (like me):
# 
# * To access Environment variables
#   > $env:<NAME>
#   (where <NAME> is the variable name)
#
# * PowerShell doesn't recognise the following as paths:
#   > $env:<PATH>/subpath
#   > $env:<PATH>\subpath
#   Instead, prefix the "call operator", like so:
#   > & $env:<PATH>/subpath
#   > & $env:<PATH>\subpath


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-2019
        - windows-2016

    steps:

    - name: Find dumpbin (VCTools)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Workload.VCTools -find **\dumpbin.exe)

    - name: Find dumpbin (MSBuildTools)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Workload.MSBuildTools -find **\dumpbin.exe)

    - name: Find dumpbin (VC.Tools)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\dumpbin.exe)

    - name: Find dumpbin (VC.Modules)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -requires Microsoft.VisualStudio.Component.VC.Modules.x86.x64 -find **\dumpbin.exe)

    - name: Find dumpbin (generic)
      if: ${{ always() }}
      run: |
        echo $(vswhere -latest -find bin\**\dumpbin.exe)
